// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one

INSERT INTO bookings (room_id, user_id, title, start_time, end_time, status, version, created_at)
VALUES ($1, $2, $3, $4, $5, $6, 1, NOW())
RETURNING id
`

type CreateBookingParams struct {
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Title     pgtype.Text        `json:"title"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Status    BookingStatus      `json:"status"`
}

// CREATE TABLE bookings (
//
//	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
//	room_id UUID NOT NULL,
//	user_id UUID NOT NULL,
//	title TEXT,
//	start_time TIMESTAMPTZ NOT NULL,
//	end_time TIMESTAMPTZ NOT NULL,
//	status booking_status NOT NULL,
//	version INTEGER NOT NULL,
//	created_at TIMESTAMPTZ DEFAULT NOW(),
//	updated_at TIMESTAMPTZ,
//	CONSTRAINT fk_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
//	CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
//
// );
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.RoomID,
		arg.UserID,
		arg.Title,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getByUserId = `-- name: GetByUserId :many
SELECT id, room_id, user_id, title, start_time, end_time, status, version, created_at, updated_at FROM bookings
WHERE user_id = $1
`

func (q *Queries) GetByUserId(ctx context.Context, userID pgtype.UUID) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Title,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIntersections = `-- name: GetIntersections :one
SELECT id, room_id, user_id, title, start_time, end_time, status, version, created_at, updated_at FROM bookings
WHERE room_id = $1
  AND STATUS IN ('pending', 'confirmed')
  AND tstzrange(start_time, end_time) && tstzrange($2, $3)
`

type GetIntersectionsParams struct {
	RoomID      pgtype.UUID `json:"room_id"`
	Tstzrange   interface{} `json:"tstzrange"`
	Tstzrange_2 interface{} `json:"tstzrange_2"`
}

func (q *Queries) GetIntersections(ctx context.Context, arg GetIntersectionsParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getIntersections, arg.RoomID, arg.Tstzrange, arg.Tstzrange_2)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Title,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
