// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// CREATE TABLE bookings (
	//   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	//   room_id UUID NOT NULL,
	//   user_id UUID NOT NULL,
	//   title TEXT,
	//   start_time TIMESTAMPTZ NOT NULL,
	//   end_time TIMESTAMPTZ NOT NULL,
	//   status booking_status NOT NULL,
	//   version INTEGER NOT NULL,
	//   created_at TIMESTAMPTZ DEFAULT NOW(),
	//   updated_at TIMESTAMPTZ,
	//   CONSTRAINT fk_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
	//   CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
	// );
	CreateBooking(ctx context.Context, arg CreateBookingParams) (pgtype.UUID, error)
	// CREATE TABLE rooms (
	//   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	//   name TEXT UNIQUE NOT NULL,
	//   capacity INTEGER NOT NULL,
	//   floor INTEGER NOT NULL,
	//   has_projector BOOLEAN NOT NULL,
	//   has_sound BOOLEAN NOT NULL,
	//   is_active BOOLEAN NOT NULL,
	//   created_at TIMESTAMPTZ DEFAULT NOW(),
	//   updated_at TIMESTAMPTZ
	// );
	CreateRoom(ctx context.Context, arg CreateRoomParams) (pgtype.UUID, error)
	// CREATE TABLE users (
	//   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	//   email TEXT UNIQUE NOT NULL,
	//   password_hash TEXT NOT NULL,
	//   first_name TEXT NOT NULL,
	//   last_name TEXT NOT NULL,
	//   role user_role NOT NULL,
	//   created_at TIMESTAMPTZ DEFAULT NOW(),
	//   updated_at TIMESTAMPTZ
	// );
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	GetByUserId(ctx context.Context, userID pgtype.UUID) ([]Booking, error)
	GetIntersections(ctx context.Context, arg GetIntersectionsParams) (Booking, error)
	GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error)
	SelectRoomForUpdate(ctx context.Context, id pgtype.UUID) (Room, error)
	UpdateRoom(ctx context.Context, arg UpdateRoomParams) error
}

var _ Querier = (*Queries)(nil)
