// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one

INSERT INTO rooms (name, capacity, floor, has_projector, has_sound, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateRoomParams struct {
	Name         string `json:"name"`
	Capacity     int32  `json:"capacity"`
	Floor        int32  `json:"floor"`
	HasProjector bool   `json:"has_projector"`
	HasSound     bool   `json:"has_sound"`
	IsActive     bool   `json:"is_active"`
}

// CREATE TABLE rooms (
//
//	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
//	name TEXT UNIQUE NOT NULL,
//	capacity INTEGER NOT NULL,
//	floor INTEGER NOT NULL,
//	has_projector BOOLEAN NOT NULL,
//	has_sound BOOLEAN NOT NULL,
//	is_active BOOLEAN NOT NULL,
//	created_at TIMESTAMPTZ DEFAULT NOW(),
//	updated_at TIMESTAMPTZ
//
// );
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Name,
		arg.Capacity,
		arg.Floor,
		arg.HasProjector,
		arg.HasSound,
		arg.IsActive,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, capacity, floor, has_projector, has_sound, is_active, created_at, updated_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.Floor,
		&i.HasProjector,
		&i.HasSound,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, capacity, floor, has_projector, has_sound, is_active, created_at, updated_at
FROM rooms
WHERE capacity >= $1 AND capacity <= $2
ORDER BY name
OFFSET $3 LIMIT $4
`

type ListRoomsParams struct {
	Capacity   int32 `json:"capacity"`
	Capacity_2 int32 `json:"capacity_2"`
	Offset     int32 `json:"offset"`
	Limit      int32 `json:"limit"`
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms,
		arg.Capacity,
		arg.Capacity_2,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Capacity,
			&i.Floor,
			&i.HasProjector,
			&i.HasSound,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectRoomForUpdate = `-- name: SelectRoomForUpdate :one
SELECT id, name, capacity, floor, has_projector, has_sound, is_active, created_at, updated_at FROM rooms
WHERE id = $1
FOR UPDATE
`

func (q *Queries) SelectRoomForUpdate(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, selectRoomForUpdate, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.Floor,
		&i.HasProjector,
		&i.HasSound,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoom = `-- name: UpdateRoom :exec
UPDATE rooms
SET name = $1, capacity = $2, floor = $3, has_projector = $4, has_sound = $5, is_active = $6, updated_at = NOW()
WHERE id = $7
`

type UpdateRoomParams struct {
	Name         string      `json:"name"`
	Capacity     int32       `json:"capacity"`
	Floor        int32       `json:"floor"`
	HasProjector bool        `json:"has_projector"`
	HasSound     bool        `json:"has_sound"`
	IsActive     bool        `json:"is_active"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.Exec(ctx, updateRoom,
		arg.Name,
		arg.Capacity,
		arg.Floor,
		arg.HasProjector,
		arg.HasSound,
		arg.IsActive,
		arg.ID,
	)
	return err
}
